### ISSUE TITLE
RetrofitError on preview

### ISSUE THREAD

**Issue by dynobo** [FauDroids/MrHyde#60]
Since yesterday i get an "that's embarrising" error, if I try to preview. Details tell me:

```
retrofit.RetrofitError: 503 Service Temporarily Unavailable
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
	at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
	at retrofit.RxSupport$2.run(RxSupport.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at retrofit.Platform$Android$2$1.run(Platform.java:142)
	at java.lang.Thread.run(Thread.java:818)
```

Any ideas?

**Comment by s1hofmann** [comment]
This was related to some maintenance downtime at our hoster over the past days. Should be resolved now.

**Comment by kusma** [comment]
I'm seeing this right now...
