### ISSUE TITLE
can't connect to gitlab

### ISSUE THREAD

**Issue by dynobo** [FauDroids/MrHyde#72]
Hey, in order to to investigate #68 I deleted my local repo and reinstalled MrHyde. 
Now I'm facing the problem, that I can't connect to gitlab anymore.

Using v1.2.0 from playstore beta channel.

I can walk-through the gitlab-setup, enter the auth-token, but then MrHyde just keeps on loading forever. If I force a stop, the reopen MrHyde and try to add gitlab again, I get following an error, with details:

```
retrofit.RetrofitError: 401 Unauthorized
at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
at retrofit.RxSupport$2.run(RxSupport.java:55)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at retrofit.Platform$Android$2$1.run(Platform.java:142)
at java.lang.Thread.run(Thread.java:818)
```

**Comment by Maddoc42** [comment]
I can confirm this. Not sure what is going on though. Just tried logging in six times, two times it worked, four times GitLab returns a 401. Some hunches for further exploration:

- Scopes: never noticed this before, but on the token page there are two options to enable scopes, which are disabled by default! MrHyde definitely needs the API scope for accessing the list of projects, possibly also the user scope for getting username and email (for git commits). Has GitLab just recently added these??

- Race condition: there might be a delay between creating an access token and it becoming valid. At least that's the only theory I can come up with right now which would explain the 2 out of 6 behavior.

Sorry for your troubles here :boat:

**Comment by dynobo** [comment]
Ha! Didn't notice these checkboxes during auth-token credation before! I checked both, and it worked immediately! :-)
Seems to be solve, for me. Thanks!

**Comment by Maddoc42** [comment]
Okay, sweet, one problem down, now back to the real problem :smile: thanks for finding this btw!

**Comment by Yuvaldv** [comment]
Linked gitlab with 2/3 check boxes (read registery left unchecked) 
Mr.hyde v.1.2.1
When connecting get an error 
'That didn't work, internal error'
'''
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.faudroids.mrhyde.gitlab.GitLabProjectOwner.getName()' on a null object reference
	at org.faudroids.mrhyde.git.RepositoryFactory.fromGitLabUser(RepositoryFactory.java:106)
	at org.faudroids.mrhyde.git.RepositoryFactory.fromGitLabProject(RepositoryFactory.java:92)
	at org.faudroids.mrhyde.gitlab.GitLabApi.lambda$getRepositories$0(GitLabApi.java:31)
	at org.faudroids.mrhyde.gitlab.GitLabApi.access$lambda$0(Unknown Source:0)
	at org.faudroids.mrhyde.gitlab.GitLabApi$$Lambda$1.call(Unknown Source:4)
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:55)
	at retrofit.RxSupport$2.run(RxSupport.java:56)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at retrofit.Platform$Android$2$1.run(Platform.java:142)
	at java.lang.Thread.run(Thread.java:764)
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: java.util.ArrayList.class
	at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:58)
	... 7 more

'''
