### ISSUE TITLE
destination path is already exists

### ISSUE THREAD

**Issue by dennyrwa** [FauDroids/MrHyde#74]
hello, I found some error in my sony xperia L that before I not get them, and my friends that using your app get error to, thanks

org.eclipse.jgit.api.errors.JGitInternalException: Destination path "brother.github.io" already exists and is not an empty directory
	at org.eclipse.jgit.api.CloneCommand.init(CloneCommand.java:152)
	at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:132)
	at org.faudroids.mrhyde.git.GitManagerFactory.lambda$cloneRepository$0(GitManagerFactory.java:67)
	at org.faudroids.mrhyde.git.GitManagerFactory.access$lambda$0(GitManagerFactory.java)
	at org.faudroids.mrhyde.git.GitManagerFactory$$Lambda$1.call(Unknown Source)
	at org.faudroids.mrhyde.utils.ObservableUtils.lambda$fromSynchronousCall$0(ObservableUtils.java:20)
	at org.faudroids.mrhyde.utils.ObservableUtils.access$lambda$0(ObservableUtils.java)
	at org.faudroids.mrhyde.utils.ObservableUtils$$Lambda$1.call(Unknown Source)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:44)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:33)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable$1.call(Observable.java:144)
	at rx.Observable$1.call(Observable.java:136)
	at rx.Observable.unsafeSubscribe(Observable.java:7495)
	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by dennyrwa** [comment]
I have solved my problem, Initially, this problem comes after i signout this app, and then try to login again, after that do the clone git and this problem arises.
This problem can be solved by deleting the clone folder in the local folder, that simple try but it work

**Comment by Maddoc42** [comment]
Great to know it is resolved :)

Do you reinstall / delete the app data between the two logins by any chance?

**Comment by ohaz** [comment]
I don't think this can be considered solved. This behaviour is still a bug. The app has to test if the directory already exists first and then decide to either delete it, or simply use it instead of cloning again.

**Comment by Maddoc42** [comment]
@ohaz it's a feature, not a bug :smile:

Strictly speaking nothing is broking, it "just" missing the feature to reuse / delete an repository which has already been cloned. Bug agreed, that would be good to have! :+1:
