### ISSUE TITLE
404 not found when previewing

### ISSUE THREAD

**Issue by kusma** [FauDroids/MrHyde#81]
When previewing a post, I get the following error:

```
retrofit.RetrofitError: 404 Not Found
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:388)
	at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
	at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
	at retrofit.RxSupport$2.run(RxSupport.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at retrofit.Platform$Android$2$1.run(Platform.java:142)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by Kulbhushan-Chand** [comment]
Same issue here

**Comment by NuttyNick** [comment]
I'm getting this issue too :'(

**Comment by Prudento-NL** [comment]
Same issue with the 'Full preview'. Never seen it working and I use the app over 2 years. Any solution or workaround?
